"""Syndrome report generation -- JSON and Markdown."""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from .scoring import SyndromeResult


def syndrome_to_json(result: SyndromeResult, path: Path) -> None:
    """Write syndrome result to JSON file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(asdict(result), indent=2), encoding="utf-8")


def syndrome_to_markdown(result: SyndromeResult) -> str:
    """Format syndrome result as Markdown report."""
    lines = [
        "# Syndrome Analysis Report",
        "",
        f"**Syndrome score:** {result.syndrome_score:.4f}",
        f"**Pairwise violation:** {result.pairwise_violation_score:.4f}",
        f"**Stability:** {result.stability_score:.4f}",
        f"**Noise sensitivity:** {result.noise_sensitivity}",
        f"**Constraints checked:** {result.n_constraints}",
        f"**Samples analyzed:** {result.n_samples}",
        "",
    ]

    if result.syndrome_score < 0.05:
        lines.append(
            "**Assessment:** Structural dependencies are preserved. No anomalies detected."
        )
    elif result.syndrome_score < 0.20:
        lines.append("**Assessment:** Minor deviations detected. Expert review recommended.")
    else:
        lines.append(
            "**Assessment:** Significant structural violations detected. Escalate for review."
        )

    if result.top_violated_pairs:
        lines.append("")
        lines.append("## Top Violated Dependencies")
        lines.append("")
        lines.append("| Feature A | Feature B | Expected rho | Actual rho | Delta | Severity |")
        lines.append("|-----------|-----------|-------------|-----------|-------|----------|")
        for p in result.top_violated_pairs:
            sev = (
                "HIGH"
                if p["violation_score"] > 0.5
                else "MEDIUM"
                if p["violation_score"] > 0.2
                else "LOW"
            )
            lines.append(
                f"| {p['feature_i']} | {p['feature_j']} | "
                f"{p['expected_rho']:.3f} | {p['actual_rho']:.3f} | "
                f"{p['delta']:.3f} | {sev} |"
            )

    lines.append("")
    lines.append("---")
    lines.append(
        "*Generated by Skeptic Engine syndrome layer. "
        "Violations indicate structural dependency breaks, not fraud. "
        "Expert review required before any conclusions about intent.*"
    )
    return "\n".join(lines)
